// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"RightPanel","status":true,"description":"","parameters":{}},
{"name":"BarrelGame","status":true,"description":"","parameters":{}},
{"name":"TileInfo","status":true,"description":"","parameters":{}}
];
